### ISSUE TITLE
Error  - newbie-

### ISSUE THREAD

**Issue by MyraBaba** [iorixxx/lucene-solr-analysis-turkish#6]
Hi,

I try to use your schema config as you wrote and the add the 2 zemberek to the solr  lib bu I have following error:

2016-12-12 18:09:44.404 ERROR (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.CoreContainer Error creating core [vitamin]: Could not load conf for core vitamin: Can't load schema /Users/myra/Downloads/solr-6.3.0/server/solr/vitamin/conf/managed-schema: Plugin init failure for [schema.xml] fieldType "text_tr": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
org.apache.solr.common.SolrException: Could not load conf for core vitamin: Can't load schema /Users/myra/Downloads/solr-6.3.0/server/solr/vitamin/conf/managed-schema: Plugin init failure for [schema.xml] fieldType "text_tr": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:85)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:840)
	at org.apache.solr.core.CoreContainer.lambda$load$0(CoreContainer.java:498)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Can't load schema /Users/myra/Downloads/solr-6.3.0/server/solr/vitamin/conf/managed-schema: Plugin init failure for [schema.xml] fieldType "text_tr": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:598)
	at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:183)
	at org.apache.solr.schema.ManagedIndexSchema.<init>(ManagedIndexSchema.java:104)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:173)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:45)
	at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:75)
	at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:107)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:78)
	... 7 more
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "text_tr": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:182)
	at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:491)
	... 14 more
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:182)
	at org.apache.solr.schema.FieldTypePluginLoader.readAnalyzer(FieldTypePluginLoader.java:399)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:104)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:53)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
	... 15 more
Caused by: org.apache.solr.common.SolrException: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:556)
	at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:625)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:382)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:375)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
	... 19 more
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:540)
	... 23 more
2016-12-12 18:09:44.407 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be created
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [vitamin]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.solr.core.CoreContainer.lambda$load$1(CoreContainer.java:526)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Unable to create core [vitamin]
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:855)
	at org.apache.solr.core.CoreContainer.lambda$load$0(CoreContainer.java:498)
	... 5 more
Caused by: org.apache.solr.common.SolrException: Could not load conf for core vitamin: Can't load schema /Users/myra/Downloads/solr-6.3.0/server/solr/vitamin/conf/managed-schema: Plugin init failure for [schema.xml] fieldType "text_tr": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:85)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:840)
	... 6 more
Caused by: org.apache.solr.common.SolrException: Can't load schema /Users/myra/Downloads/solr-6.3.0/server/solr/vitamin/conf/managed-schema: Plugin init failure for [schema.xml] fieldType "text_tr": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:598)
	at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:183)
	at org.apache.solr.schema.ManagedIndexSchema.<init>(ManagedIndexSchema.java:104)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:173)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:45)
	at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:75)
	at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:107)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:78)
	... 7 more
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "text_tr": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:182)
	at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:491)
	... 14 more
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:182)
	at org.apache.solr.schema.FieldTypePluginLoader.readAnalyzer(FieldTypePluginLoader.java:399)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:104)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:53)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
	... 15 more
Caused by: org.apache.solr.common.SolrException: Error loading class 'org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory'
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:556)
	at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:625)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:382)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:375)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
	... 19 more
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.tr.Zemberek3StemFilterFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:540)
	... 23 more

**Comment by iorixxx** [comment]
Hi,

It looks like you didn't include the TurkishAnalysis*.jar, which can be generated by issuing mvn package. Thus, you need three: zemberek-morphology-0.9.2.jar zemberek-core-0.9.2.jar TurkishAnalysis-6.3.0.jar Please let me know if you have further troubles.

**Comment by MyraBaba** [comment]
Thanks…

i am trying it now.. solr 6.3.0 

…

We used before (solr 4 )  and found that there is a huge memory leak on that version of zemberek. 

Also attached the lib folder snap.

and tried :

2016-12-12 18:55:17.798 ERROR (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.CoreContainer Error creating core [tiamin]: org/apache/lucene/analysis/util/ResourceLoaderAware
java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/ResourceLoaderAware
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:540)
	at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:625)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:382)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:375)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
	at org.apache.solr.schema.FieldTypePluginLoader.readAnalyzer(FieldTypePluginLoader.java:399)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:104)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:53)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
	at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:491)
	at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:183)
	at org.apache.solr.schema.ManagedIndexSchema.<init>(ManagedIndexSchema.java:104)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:173)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:45)
	at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:75)
	at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:107)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:78)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:840)
	at org.apache.solr.core.CoreContainer.lambda$load$0(CoreContainer.java:498)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.util.ResourceLoaderAware
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
2016-12-12 18:55:17.801 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be created
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/ResourceLoaderAware
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.solr.core.CoreContainer.lambda$load$1(CoreContainer.java:526)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/ResourceLoaderAware
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:540)
	at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:625)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:382)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:375)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
	at org.apache.solr.schema.FieldTypePluginLoader.readAnalyzer(FieldTypePluginLoader.java:399)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:104)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:53)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
	at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:491)
	at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:183)
	at org.apache.solr.schema.ManagedIndexSchema.<init>(ManagedIndexSchema.java:104)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:173)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:45)
	at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:75)
	at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:107)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:78)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:840)
	at org.apache.solr.core.CoreContainer.lambda$load$0(CoreContainer.java:498)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.util.ResourceLoaderAware
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more

**Comment by MyraBaba** [comment]
Hi There,

What I tried so far:

I added zemberek-core-0.9.3  , zemberek-morphology-0.9.3 and TurkishAnalysis-6.3.0  jars to the lib. 

First of all I got:

java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/ResourceLoaderAware

Error.
Than I added the :  lucene-analyzers-common-6.3.0  to the lib. (I read somewhere in the net)

Than a new Error:

Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.TokenStream


So I stuck here :)


if you have time I would love to talk via online.

thx

**Comment by iorixxx** [comment]
> Than I added the :  lucene-analyzers-common-6.3.0  to the lib. 

This is not necessary, solr distribution already contains that.

Please download  solr630 from scratch and make a fresh installation.
You need exactly three jars : 

1. TurkishAnalysis-6.3.0.jar 
2. core-0.9.2.jar 
3. morphology-0.9.2.jar

Here is the shell script that copies the three jars into a lib directory.

``` sh
git clone https://github.com/iorixxx/lucene-solr-analysis-turkish.git
cd lucene-solr-analysis-turkish
mkdir -p lib
mvn clean package
cp ~/.m2/repository/zemberek-nlp/morphology/0.9.2/morphology-0.9.2.jar lib
cp ~/.m2/repository/zemberek-nlp/core/0.9.2/core-0.9.2.jar lib
cp target/TurkishAnalysis-*.jar lib
```

**Comment by iorixxx** [comment]
> if you have time I would love to talk via online.

Sure, my Skype handle is iorixxxx, please add me.

**Comment by MyraBaba** [comment]
Hi,

I followed exactly the steps you described below. fress solr 6.3.0..

started sold with  bin/solr start -f   (default  server  path)

created a core with bin/solr create -c ionic

add scheme to turkish nlp as attached document.

copied :

TurkishAnalysis-6.3.0.jar
core-0.9.2.jar
morphology-0.9.2.jar
to the server/lib  path.

restart/reload the solr.

and I have :


2016-12-13 11:03:00.881 ERROR (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.CoreContainer Error creating core [ionic]: org/apache/lucene/analysis/util/ResourceLoaderAware
java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/ResourceLoaderAware


Something I am missing very stupid .


thx

















Here is the shell script that copies the three jars into a lib directory.

git clone https://github.com/iorixxx/lucene-solr-analysis-turkish.git <https://github.com/iorixxx/lucene-solr-analysis-turkish.git>
cd lucene-solr-analysis-turkish
mkdir -p lib
mvn clean package
cp ~/.m2/repository/zemberek-nlp/morphology/0.9.2/morphology-0.9.2.jar lib
cp ~/.m2/repository/zemberek-nlp/core/0.9.2/core-0.9.2.jar lib
cp target/TurkishAnalysis-*.jar lib

**Comment by iorixxx** [comment]
> to the server/lib  path

This is the cause. The correct path should be solr-6.3.0/server/solr/xxx/lib
Please close the issue when you have get things running.

**Comment by MyraBaba** [comment]
Thanks a lot. 

problem solved with correct lib path and the jars.
