### ISSUE TITLE
TurkishAnalysis jar file

### ISSUE THREAD

**Issue by ceatlinar** [iorixxx/lucene-solr-analysis-turkish#8]
I am trying to build a core with Zemberek support as you have created one with a link to it in Readme file. But I need to create this core inside of Solr 7.0.0. I have tried to follow the steps but having problems. 

First of all, you mention 3 jar files (TurkishAnalysis-6.3.0.jar, core-0.9.2.jar, morphology-0.9.2.jar). For my Solr 7 version TurkishAnalysis jar file should be TurkishAnalysis-7.0.0.jar I believe but I couldnt obtain jar file, how can I obtain. And does the version of other jar files cause a conflict? Because I can't find them as well

Secondly, it would be great if you could give me a step by step instruction on how to create a core with zemberek support in Solr 7.0.0. Below, there are steps I tried to follow:

1 -  get neccesarry jar files into a lib directory inside of the core I want
2 - add field type definition for Turkish inside schema file of the core

Lastly I wanted to ask if it is obligatory to have a Maven project or can we create this core with a regular Java project ?

**Comment by iorixxx** [comment]
Can't you just upgrade to Solr version 8.1? The issue is https://issues.apache.org/jira/browse/SOLR-11260 resolved in that version. So you don't need to patch and rebuild Solr. If Solr 7.0.0 is a must, unfortunately, patching/rebuilding Solr is inevitable. This is somehow independent of the Turkish analysis plugin. https://issues.apache.org/jira/browse/SOLR-11763 is the code that fixed the Guava issue.

**Comment by ceatlinar** [comment]
Solr 7.0.0 is a must, unfortunately. But I don't know how to do it. As much I could figure out (correct me if I am wrong) this repo creates a jar file named TurkishAnalysis. Does this file have to have same version with the Solr. Because I can't seem to create a TurkishAnalysis7.0.0.jar file. If not obligatory, could you please help me how to patch/rebuild solr because I am new with the whole Solr System. Also, I sent you a Skype request. If you could accept it maybe I could explain more detailed what I am trying to do so that you could help me out better maybe

**Comment by iorixxx** [comment]
The version of the TurkishAnalysis.jar does not need to be same with the Solr version you are using. Regarding patching and rebuilding, please read the 'Working with patches' and 'Building the first time' subsections in https://cwiki.apache.org/confluence/display/solr/HowToContribute . Can't you use Solr version 7.3.0? You can download already patched distribution from  https://www.dropbox.com/s/yygdvwoe4cc7d46/solr-7.3.0.tgz

**Comment by ceatlinar** [comment]
Like I said before, version 7.0.0 is a must. I already download and tested your patched solr 7.3 to understand. In fact I tried to copy zemberek collection from your patched version 7.3.0 to unpatched version 7.3.0. It gave com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List; error which is a Guava error I believe because it was solved when I replaced guava-14.0.1.jar with guava-23.0 underneath server\solr-webapp\webapp\WEB-INF\lib. But when I tried to do same thing with solr 7.0.0, I copied zemberek collection from your patched version 7.3 to unpatched 7.0.0, it gave same com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List;  error but wasnt solved this time when I replaced guava jar file with guava-23.0. This time it gives opening new searcher error. When checking log I find following info :

null:org.apache.solr.core.SolrCoreInitializationException: SolrCore 'zemberek' is not available due to init failure: Error opening new searcher
	at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1403)
	at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:267)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:480)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:378)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:322)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:988)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:843)
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:980)
	at org.apache.solr.core.CoreContainer.lambda$load$117(CoreContainer.java:619)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$128(ExecutorUtil.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
	at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:2066)
	at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:2186)
	at org.apache.solr.core.SolrCore.initSearcher(SolrCore.java:1071)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:960)
	... 9 more
Caused by: org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\atlin\Desktop\solrs\solr-7.0.0\server\solr\zemberek\data\index\segments_u"))): 8 (needs to be between 6 and 7)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:305)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:289)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1076)
	at org.apache.solr.update.SolrIndexWriter.<init>(SolrIndexWriter.java:119)
	at org.apache.solr.update.SolrIndexWriter.create(SolrIndexWriter.java:94)
	at org.apache.solr.update.DefaultSolrCoreState.createMainIndexWriter(DefaultSolrCoreState.java:257)
	at org.apache.solr.update.DefaultSolrCoreState.getIndexWriter(DefaultSolrCoreState.java:131)
	at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:2027)
	... 12 more


what I wonder is should I patch guava file or should I try to patch solr from scratch. If  I should patch guava, should I use the link you provıded on your first answer and if I should patch solr, how can I use your patched solr and zemberek collection

**Comment by iorixxx** [comment]
You need to patch and rebuild Apache Solr 7.0.0. You cannot use my patched solr, since it is based on the vesion 7.3.0.

**Comment by ceatlinar** [comment]
Okaay. Now what I finally wonder is: when patching and rebuilding Solr 7.0.0, can I use your repo to make a zemberek plugin inside this Solr 7.0.0 or should I somehow create a new repo from scratch to make a zemberek plugin. If I somehow can use your repo to make a zemberek plugin inside my own Solr 7.0.0, could you please give me some hints on how to do it.

**Comment by iorixxx** [comment]
What do you mean by saying my repo?

**Comment by ceatlinar** [comment]
What I mean is, when the code in your github repo is run with the maven command you mentioned in Readme, creates jar files. Could the code or jar files be used for a plugin in Solr 7

**Comment by iorixxx** [comment]
jar files can be used for a plugin in Solr 7

**Comment by ceatlinar** [comment]
Thank you
